### ISSUE TITLE
healthCheck requires at least one check to be valid

### ISSUE THREAD

**Issue by robinmarr-ft** [Financial-Times/express-web-service#17]
The docs suggest that healthCheck is optional configuration but the default response does not  return any valid checks, causing the [Healthcheck Validator](http://healthcheck.ft.com/validate?host=ft-intprod-deeperview-api-t.herokuapp.com&server=ft-intprod-deeperview-api-t.herokuapp.com&protocol=https) to fail.

The healthCheck default should be changed to:
```js  
healthCheck: () => Promise.resolve([ { ok: true } ]),
```
So at least one check is sent by default.

**Comment by JakeChampion** [comment]
@robinmarr-ft Thanks for the issue, I've replicated the issue on a demo application. Your proposed solution would work, are you happy to submit a PR which for this?

**Comment by robinmarr-ft** [comment]
I have a PR ready but no perms to push it 😕

**Comment by JakeChampion** [comment]
You now have permission :-)

**Comment by JakeChampion** [comment]
Fixed via #18
