### ISSUE TITLE
Limitations of approach unusual for express middleware

### ISSUE THREAD

**Issue by pornel** [Financial-Times/express-web-service#5]
Interface for adding these routes is unusual for express. Typically middlewares are attached via `app.use()` 

The current design creates some difficulties for the webapp:
- In the webapp we have our own middleware that attaches extra properties to the request. But this service integration doesn't expose the usual `res`/`req`/`next`, so we can't access our request properties and need to make them global.
- Our `__about` needs to get version, which is asynchronous (because in dev it calls `git describe`). We can't do that with literal opts.about. We also expose `req.secure` in __about for debugging. Without access to `req` we can't.

**Comment by pornel** [comment]
I'm not entirely sure how a more express-like approach should look like, but perhaps something along lines of:

```js
app.use(fthealthchecks({config:goes here}));

app.get('__gtg' /* or insert route abstraction here */, (req, res, next) => {
    res.ftgtgRespondWith(ourHealthcheckFunction());
});
```

**Comment by rowanbeentje** [comment]
I thought the `__about` special requirements could largely be handled by allowing the definition to optionally return a promise resolving to the object - that would let apps do what they want and still support the simple object/package.json definition

**Comment by JakeChampion** [comment]
🎉
